### ISSUE TITLE
nlp/feature-vector/벡터 간 유사도 비교하는 방법

### ISSUE THREAD

**Issue by heeejoo0518** [kookmin-sw/2019-cap1-2019_12#23]
1. 서브벡터로 비교
- 벡터간 비교를 위해 서브벡터를 만든다. 
- (비교하는 벡터끼리 단어 순서와 인덱스가 일치해야하기 때문)

**Comment by hyein15** [comment]
2.  tf-idf 값이 높은 단어들 위주로 특징 벡터를 만들어 유사도를 비교
- 단어의 tf-idf 값이 높을 수록 그 문서의 고유한 특성이 될 수 있기 때문에 tf-idf 값이 낮은 단어들은 제외하여 비교해본다

**Comment by heeejoo0518** [comment]
3. 코사인 유사도를 이용하지 않고 단어 빈도만을 이용해 유사도를 비교
* 벡터들이 같은 기준, 같은 데이터셋으로 만들어진게 아니기 때문에 코사인 유사도를 이용하기에는 무리가 있을 수 있다.

**Comment by heeejoo0518** [comment]
4/12 회의
벡터 만드는 방식을 바꾸면서 자연스럽게 벡터 비교하는 방법도 바뀜.
항목별 벡터의 tf-idf값 합친 수치로 기업별, 직무별, 사용자 벡터(행렬) 만듦
-> 코사인 유사도는 (일치도 높은 상위 기업 3개) 그래프 표현 할 때만 사용.

**Comment by heeejoo0518** [comment]
#32 와 합쳐진 내용
