### ISSUE TITLE
nlp/data-refine/한국어 불용어 리스트 수집

### ISSUE THREAD

**Issue by hyein15** [kookmin-sw/2019-cap1-2019_12#25]
데이터 수집 후 정제 과정에서 불필요한 단어들이 많아 처리 시간이 매우 오래 걸림
한국어 불용어 정보를 수집하여 무의미한 단어들을 삭제하도록 해야함

**Comment by hyein15** [comment]
불용어 정보-1
https://www.ranks.nl/stopwords/korean?fbclid=IwAR2ExNUknGf4bOHA3cECFrv50f8YO2WOTEV4XKP5iDFAANYFWJ1PbMu9j_k

**Comment by hyein15** [comment]
불용어 정보-2
https://github.com/stopwords-iso/stopwords-ko?fbclid=IwAR39k6XIYRN7fFahioaRHu8h2-IBp-vNMShwGMR92n8xlby8LJ6O1VwjHvc

**Comment by hyein15** [comment]
불용어 정보-3
https://gist.github.com/spikeekips/40eea22ef4a89f629abd87eed535ac6a

**Comment by heeejoo0518** [comment]
4. [https://bab2min.tistory.com/544](url)
---현재 불용어 리스트에 1,4 저장되어 있음

**Comment by heeejoo0518** [comment]
1~4 전부 합침
stopwords 파일 클라우드에 저장.
