### ISSUE TITLE
nlp/model/문서 분류 모델 구현 연구

### ISSUE THREAD

**Issue by hyein15** [kookmin-sw/2019-cap1-2019_12#32]
문서 분류 모델을 구현하기 위한 알고리즘에 대해 연구한다

**Comment by heeejoo0518** [comment]
* 기계학습(sklearn)
1. Rocchio
2. SVM
3. KNN
..
* 딥러닝(tensorflow)
1. CNN
2. RNN
..

**Comment by heeejoo0518** [comment]
텍스트 분류 과정
* **데이터 분석과정(EDA - 탐색적 자료 분석) 필요**
* 데이터 정제
* 모델링
* 성능평가

**Comment by heeejoo0518** [comment]
SVM으로 분류하면 면적을 비선형or선형으로 나눔->점과 면적? 면적과 면적 간 최대거리,최소거리,평균거리 셋 중 하나 구해서 순서 매겨야 할 것 같음. 그 과정에서 나오는 수치를 저장하는 방법이 있다.

**Comment by heeejoo0518** [comment]
SVM decision function - predict 관계(vote)
https://stackoverflow.com/questions/20113206/scikit-learn-svc-decision-function-and-predict
```
# This replicates clf.predict(X)
def predict(params, sv, nv, a, b, cs, X):
    ''' params = model parameters
        sv = support vectors
        nv = # of support vectors per class
        a  = dual coefficients
        b  = intercepts 
        cs = list of class names
        X  = feature to predict       
    '''
    decision = decision_function(params, sv, nv, a, b, X)
    votes = [(i if decision[p] > 0 else j) for p,(i,j) in enumerate((i,j) 
                                           for i in range(len(cs))
                                           for j in range(i+1,len(cs)))]

    return cs[max(set(votes), key=votes.count)]
```

**Comment by hyein15** [comment]
![image](https://user-images.githubusercontent.com/22020545/57572387-6d386c80-7454-11e9-8483-4ccf88d24f8a.png)

decision_function을 사용한 결과

**Comment by heeejoo0518** [comment]
![image](https://user-images.githubusercontent.com/42292066/57584685-fe711700-7518-11e9-9767-9f3d865f69e8.png)
더 나은 예측모델을 만들 필요성이 있음. 손실함수값 조정+데이터 정제에 문제가 있는 것 같다.

**Comment by heeejoo0518** [comment]
![image](https://user-images.githubusercontent.com/42292066/57595504-69096d80-7580-11e9-9bc4-a64b9dc8bbcb.png)
단어예측은 완벽하게 잘 되었고, 테스트 데이터는 0.82점이 나왔다.

**Comment by heeejoo0518** [comment]
완성한 모델은 pickle 형태로 joblib을 사용해서 저장&로드 가능.
python 3에서 저장한 pickle파일은 python 3에서만 읽을 수 있다는 점을 주의해야 함!
https://gaussian37.github.io/ml-sklearn-saving-model/
http://blog.naver.com/wideeyed/221330321950

**Comment by heeejoo0518** [comment]
![image](https://user-images.githubusercontent.com/42292066/57855046-b279e700-7824-11e9-9aa8-8c5f9bf787fe.png)

적은 데이터에서 SVC 모델이 더 나은 점수를 보였다.

**Comment by heeejoo0518** [comment]
클래스 분류 방식
- one vs one
- one vs rest(= one vs all)
어떤 방식을 선택할 지 고민..

**Comment by heeejoo0518** [comment]
![image](https://user-images.githubusercontent.com/42292066/57863601-59ff1580-7835-11e9-8b6f-ca4ae164fa1b.png)
많은 양의 데이터에서도 SVC모델이 가장 성능이 좋았다.

**Comment by heeejoo0518** [comment]
SVC 선택
