### ISSUE TITLE
nlp/model/svm 모델 구현

### ISSUE THREAD

**Issue by hyein15** [kookmin-sw/2019-cap1-2019_12#34]
합격 자기소개서와 사용자 입력 자기소개서가 10개의 각 역량들을 바탕으로 어떤 성향을 띄고 있는지 분석하기 위한 svm 문서 분류 모델을 구현한다.

**Comment by heeejoo0518** [comment]
학습 데이터 양을 늘렸더니 테스트 데이터 점수는 높아졌지만 (82점->91점) 간단한 문장에 대해서 예상하지 못한 결과가 나왔다.
ex) 능동적인 사람이 되자->주인의식으로 예측

**Comment by heeejoo0518** [comment]
데이터 양을 더 늘렸더니 점수는 비슷했지만 간단한 문장에서 더 나은 성능을 보인다. 그러나 단어들에 대해서는 아직 의문이 드는 부분이 있다.
![image](https://user-images.githubusercontent.com/42292066/57774934-c35c2700-7756-11e9-9e08-e88586dfda9f.png)

**Comment by heeejoo0518** [comment]
모델을 저장할 때 새로운 버전의 joblib를 사용해야 한다.
https://stackoverflow.com/questions/48948209/keyerror-when-loading-pickled-scikit-learn-model-using-joblib

**Comment by heeejoo0518** [comment]
#32 에서 구한 SVC모델 선택
