### ISSUE TITLE
nlp/data-crawling/역량별 문장의 저장 형식 변경

### ISSUE THREAD

**Issue by hyein15** [kookmin-sw/2019-cap1-2019_12#35]
크롤링한 역량별 문장을 txt 형식 대신 csv 형식으로 저장하도록 코드 수정해야함

**Comment by hyein15** [comment]
#14 번 브랜치는 이미 data_crawling에 merge를 한 상태여서 data_crawling 브랜치에 수정함

**Comment by heeejoo0518** [comment]
bfa9229383806bf53565fe984c6805fee28cb1dd 4e6d9f761e8902ca02603a08b8c836f65789464f
