### ISSUE TITLE
nlp/module/SVM 사용자 자기소개서 분석 모듈

### ISSUE THREAD

**Issue by heeejoo0518** [kookmin-sw/2019-cap1-2019_12#38]
파이썬 서버에 들어갈 자연어처리 모듈을 만든다.
- [x] 사용자 자소서를 미리 저장된 모델에 넣어 예측
- [x] 사용자 자소서-기업 비교(모델 이용) #50 
- [x] 사용자 자소서 예측값(predict_proba) * 100 
- [x] 사용자 자소서-기업(선택기업, 일치기업) 상대적 예측값 계산
- [x] 비교한 결과를 json으로 모두 정리

**Comment by nuseehr** [comment]
<img width="768" alt="스크린샷 2019-05-13 오후 11 47 03" src="https://user-images.githubusercontent.com/26623501/57630906-70a93080-75d9-11e9-835a-07e98b42eacc.png">

벡터값 비교위한 수치보정 단계는 위 이미지와 같은 방법을 적용해보기.

**Comment by heeejoo0518** [comment]
문항별, 전체 자기소개서 모두 비교해야 한다.

**Comment by heeejoo0518** [comment]
완성한 모델은 joblib을 사용해서 pickle 형태로 저장.
python 3에서 저장한 pickle파일은 python 3에서만 읽을 수 있다는 점을 주의해야 함!
https://gaussian37.github.io/ml-sklearn-saving-model/
http://blog.naver.com/wideeyed/221330321950

**Comment by heeejoo0518** [comment]
필요한 라이브러리 목록
- scikit-learn
        - numpy, scipy, joblib
- konlpy
        - Jpype1

**Comment by hyein15** [comment]
(합격 자기소개서의 핵심역량별 값 - 사용자 자기소개서의 핵심역량별 값) 을 구한 뒤 
기업별로 합해 가장 낮은 값을 가진 순으로 정렬한다. 이를 통해 사용자에게 가장 적합한 기업을 알 수 있다

**Comment by heeejoo0518** [comment]
![image](https://user-images.githubusercontent.com/42292066/57867717-971ad600-783c-11e9-865c-e5b4eee46415.png)
![image](https://user-images.githubusercontent.com/42292066/57867777-b4e83b00-783c-11e9-86a0-1964996667e6.png)

분석하는데 걸리는 시간보다 모델을 로드하는데 걸리는 시간이 훨씬 많이 든다.

**Comment by heeejoo0518** [comment]
![image](https://user-images.githubusercontent.com/42292066/57937134-4e2c5580-7900-11e9-9e80-2838da69fc2e.png)
예측결과가 tuple list 로 리턴됨

**Comment by heeejoo0518** [comment]
model scikit-learn version 0.20.3
