### ISSUE TITLE
nlp/data-crawling/역량별 keyword 변경

### ISSUE THREAD

**Issue by hyein15** [kookmin-sw/2019-cap1-2019_12#39]
명사로 크롤링 하게 되면 관련 없는 문장까지 크롤링 되기 때문에 여러가지 상황을 고려하여야 하므로 크롤링 하는 단어를 변경하여 보다 정확한 문장을 수집하도록 한다. 

1. 명사 위주의 키워드를 관형사로 변경 ex) '열정' 이라는 단어를 '열정적', '열정적인' 으로 변경
2. 동음이의어 제거
3. 자주 나오지만 관련 없는 단어 ex)문화와 문화상품권..

**Comment by hyein15** [comment]
data_crawling 브랜치에 반영할 예정

**Comment by heeejoo0518** [comment]
네이버 크롤링은 data_crawling_#13 에 수정된 키워드 반영할 예정

**Comment by heeejoo0518** [comment]
keyword_1 = ["문화 -문화상품권", "국제적", "외국어"] #글로벌역량
keyword_2 = ["능동적", "열정적", "적극적"] #능동
keyword_3 = ["도전적", "모험", "담력"] #도전
keyword_4 = ["성실한", "근면한", "충실한"] #성실
keyword_5 = ["소통", "대화", "교류"] #소통
keyword_6 = ["인내심", "끈기", "근성"] #인내심
keyword_7 = ["정직한","진실", "솔직"] #정직
keyword_8 = ["책임","의무", "자기주도"] #주인의식
keyword_9 = ["창의적", "창조","독창"] #창의
keyword_10 = ["팀워크", "협력", "협동"] #팀워크

**Comment by heeejoo0518** [comment]
keyword_3 = ["도전적", "모험", "용기있는"] #도전
변경
